This is makeindex, version 2.15 [TeX Live 2012] (kpathsea + Thai support).
Scanning style file ./CSS_BP_UTF-8.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file CSS_BP_UTF-8.acn....done (1 entries accepted, 0 rejected).
Sorting entries...done (0 comparisons).
Generating output file CSS_BP_UTF-8.acr....done (6 lines written, 0 warnings).
Output written in CSS_BP_UTF-8.acr.
Transcript written in CSS_BP_UTF-8.alg.
